name: Pull and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像名称

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clean up Docker to free space
      run: |
        docker system prune -a -f
        docker volume prune -f

    - name: Pull Docker Image and Package
      run: |
        image="${{ github.event.inputs.docker_image }}"
        docker pull "${image}" --platform "linux/amd64"

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Push Image to Docker Registry
      run: |
        image="${{ github.event.inputs.docker_image }}"
        docker tag "${image}" "${{ secrets.DOCKER_REGISTRY }}/${image}"
        docker push "${{ secrets.DOCKER_REGISTRY }}/${image}"

    - name: Logout from Docker Registry
      run: docker logout ${{ secrets.DOCKER_REGISTRY }}